# Disable the spring security default configuration from spring-boot-actuator
management.security.enabled: true
security.basic.enabled: false

# Disable Jolokia - An http/json bridge for remote JMX access
endpoints.jolokia.enabled: false

# security configuration (this key should be unique for your application, and kept secret)
jhipster.security.rememberme.key: 3cecb2cb3dc81855c36724624177948278173a10

async:
    corePoolSize: 2
    maxPoolSize: 50
    queueCapacity: 10000

multipart:
    file-size-threshold: 10Mb
    max-file-size: 1Mb
    max-request-size: 10Mb

spring:
    mail:
        host: smtp.gmail.com
        port: 587
        user: nummap1
        password: xdlolwtf31
        protocol: smtp
        tls: yes
        auth: yes
        from: no-reply@nummap.com

    messageSource:
        cacheSeconds: 1




swagger:
    title: nummap API
    description: nummap applications and beyond!
    termsOfServiceUrl: http://jhipster.github.io/
    contact:
    license: Apache 2.0
    licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
